#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Rally on Supabase Pro + Vercel Pro. Run from the rally/ directory
# on a machine where you are logged into both dashboards. Idempotent: re-run
# any time; values already in .env are kept unless you re-enter them.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.env}"

banner "Rally — provision Supabase and Vercel"

stage "Supabase project"
say "Rally gets its own Supabase project inside your Pro organisation. Pro projects"
say "never pause, and the \$10 compute credit covers a Micro instance (ADR-034)."
open_url "https://supabase.com/dashboard/projects"
step "New project → pick your Pro organisation."
step "Name: rally. Region: the US region closest to your first cluster — note it, Vercel pins to it."
step "Generate a strong database password and keep it in your password manager."
step "Wait for the project to finish provisioning, then open Project Settings → General."
ask     SUPABASE_PROJECT_REF "Reference ID (short lowercase string under the project name)"
ask     SUPABASE_REGION      "Region as shown (e.g. us-east-1)"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env SUPABASE_REGION "$SUPABASE_REGION"
pause

stage "Database connection strings"
say "Two URLs. The app uses the transaction-mode pooler on port 6543 (serverless-safe,"
say "prepared statements off). Migrations use session mode on 5432."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/database"
step "Click 'Connect' → Connection string → choose 'Transaction' mode → copy the URI (port 6543)."
ask_secret DATABASE_URL "Transaction-mode URL (port 6543)"
step "Now choose 'Session' mode → copy the URI (port 5432)."
ask_secret DATABASE_URL_SESSION "Session-mode URL (port 5432, for migrations)"
write_env DATABASE_URL "$DATABASE_URL"
write_env DATABASE_URL_SESSION "$DATABASE_URL_SESSION"
pause

stage "API keys"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api"
step "Copy the Project URL."
ask SUPABASE_URL "Project URL (https://….supabase.co)"
step "Copy the 'anon public' key — safe for the browser."
ask_secret SUPABASE_ANON_KEY "anon key"
step "Reveal and copy the 'service_role' key — server only, never shipped to a client."
ask_secret SUPABASE_SERVICE_ROLE_KEY "service_role key"
step "Under JWT Settings, copy the JWT Secret — the API verifies tokens with it."
ask_secret SUPABASE_JWT_SECRET "JWT secret"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
write_env SUPABASE_JWT_SECRET "$SUPABASE_JWT_SECRET"
pause

stage "Auth providers — Apple and Google"
say "Sign-in is Apple and Google with email OTP as the fallback (spec story 8)."
say "Both providers need credentials from their own consoles. If you don't have them"
say "yet, skip this stage — email OTP works today and this stage can be re-run later."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "Email: ensure it is enabled with 'Confirm email' on."
step "Google: enable, then paste the OAuth Client ID and Secret from Google Cloud Console"
step "  (APIs & Services → Credentials → OAuth 2.0 Client, type Web; add the Supabase callback URL shown)."
step "Apple: enable, then paste the Services ID, Team ID, Key ID and the .p8 key contents from"
step "  developer.apple.com (Certificates, Identifiers & Profiles → Keys → Sign in with Apple)."
if confirm "Did you configure at least Google or Apple now?"; then
  write_env AUTH_PROVIDERS_CONFIGURED "true"
else
  write_env AUTH_PROVIDERS_CONFIGURED "false"
  say "Noted. Email OTP is the only sign-in until this stage is re-run."
fi
pause

stage "Extensions and scheduled jobs"
say "Rally uses PostGIS for geography and pg_cron + pg_net for timed transitions (ADR-034)."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/database/extensions"
step "Search 'postgis' → enable. Search 'pg_cron' → enable. Search 'pg_net' → enable."
step "Do not look for h3 — it is not available on Supabase; Rally uses PostGIS instead."
pause "All three enabled?"

stage "Vercel project"
say "One Vercel project, root directory 'rally', functions pinned to the Supabase region."
open_url "https://vercel.com/new"
step "Import the AushadiExpress repository (or the repo Rally lives in)."
step "Project name: rally. Framework preset: Other. Root Directory: rally."
step "Do NOT deploy yet — open Settings after creation."
step "Settings → Functions → Function Region: choose the region matching ${SUPABASE_REGION:-your Supabase region}."
step "Settings → General → copy the Project ID; Settings → your team → copy the Team ID."
ask VERCEL_PROJECT_ID "Project ID (prj_…)"
ask VERCEL_ORG_ID "Team ID (team_…)"
write_env VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
write_env VERCEL_ORG_ID "$VERCEL_ORG_ID"
pause

stage "Vercel environment variables"
say "Paste the values captured above into the Vercel project so previews and production"
say "can reach Supabase. Mark the secrets 'Sensitive'. Apply to Production and Preview."
open_url "https://vercel.com/dashboard"
step "Open the rally project → Settings → Environment Variables. Add each of:"
step "  DATABASE_URL, SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_JWT_SECRET"
step "  (values are in your local ${ENV_FILE} — copy from there; never paste them into a chat)."
step "Add MIN_SUPPORTED_CLIENT = 0.1.0 (plain, not sensitive)."
pause "All variables added?"

finish
